spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/patient_events}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: ${SPRING_LIQUIBASE_CHANGE_LOG:file:../docs/schemas/liquibase.yaml}

server:
  port: 8080
